### PR TITLE
updated scenarios to new notation

### PR DESCRIPTION
**Pull request by max-pilz**

### CODE REVIEW

**Comment by kkmann** [comment]
the problem might be a naming conflict with purrr::compose; purrr is implicitly loaded via tidyverse, so this is not good x) any alternatives to compose? composite?

**Comment by max-pilz** [comment]
> 
> 
> the problem might be a naming conflict with purrr::compose; purrr is implicitly loaded via tidyverse, so this is not good x) any alternatives to compose? composite?

No, I think that the problem is:

https://github.com/kkmann/adoptr-validation-report/blob/669e0f87b28fa792cd3a136a39d187ef464fcfdd/05-scenario-V.Rmd#L177-L180

Here, "compose" does not recognize lambda to be integer. Calling
"evaluate(obj(100), init_design(5))"
returns
"object 'lambda' not found"

I think about how to fix this

**Comment by kkmann** [comment]
@MatheMax just pushed a hotfix to adoptr enabling the use of non-score variables in compose expressions; the naming issue is still a thing though (i.e., our compose will not work if you load the tidyverse afterwards)

**Comment by kkmann** [comment]
looking good ;)

**Pull request merged**
